server {
    listen 80 default_server;
    server_name _;
    root /var/www/html/public;
    index index.php;

    # Alles an die index.php leiten
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # PHP Verarbeitung
    location ~ \.php$ {
        # Falls die Datei physisch nicht da ist, direkt Nginx-404 statt PHP-Fehler
        try_files $uri =404;
        
        include fastcgi_params;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        
        # Absolute Pfade für PHP-FPM
        fastcgi_param SCRIPT_FILENAME /var/www/html/public$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT /var/www/html/public;
    }

    location /assets/ {
        access_log off;
    }
}