server {
    listen 80 default_server;
    listen [::]:80 default_server;
    
    server_name _;
    root /var/www/html/public;
    index index.php index.html;

    # Debugging aktivieren
    error_log  /var/log/nginx/error.log warn;
    access_log /var/log/nginx/access.log;

    location / {
        # Zuerst schauen ob Datei da ist, sonst an index.php
        try_files $uri $uri/ /index.php?$query_string;
    }

    # PHP-FPM
    location ~ \.php$ {
        # Wenn die .php Datei physisch nicht existiert -> 404
        if (!-f $document_root$fastcgi_script_name) {
            return 404;
        }

        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    # Assets
    location /assets/ {
        try_files $uri =404;
    }
}